# Generated by Django 3.2.12 on 2022-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20220418_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='image',
            field=models.ImageField(default='guide/default.jpg', upload_to='guide/'),
        ),
        migrations.AddField(
            model_name='paper',
            name='category',
            field=models.ManyToManyField(to='guide.Category'),
        ),
    ]
