# Generated by Django 3.2.12 on 2022-04-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0003_auto_20220419_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='translator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='guide.Category'),
        ),
    ]
